In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(f"{arr} Original Array")
print(f"{arr+5} Adding 5 to each element in Array")
print(f"{arr*3} Multiplying 3 by each element in Array")
print(f"{arr**2} Square of Each Element")

[1 2 3 4 5 6 7 8 9] Original Array
[ 6  7  8  9 10 11 12 13 14] Adding 5 to each element in Array
[ 3  6  9 12 15 18 21 24 27] Multiplying 3 by each element in Array
[ 1  4  9 16 25 36 49 64 81] Square of Each Element


In [5]:
# Sum of Two Arrays
ar=np.array([10,20,30])
ar1=np.array([5,8,9])
sum=ar+ar1
print(f"Sum of the Two arrays = {sum} ")

Sum of the Two arrays = [15 28 39] 


In [6]:
# Sub of Two Arrays
ar=np.array([10,20,30])
ar1=np.array([5,8,9])
sub=ar-ar1
print(f"Subtraction of the Two arrays = {sub} ")

Subtraction of the Two arrays = [ 5 12 21] 


In [7]:
# Multiplication of Two Arrays
ar=np.array([10,20,30])
ar1=np.array([5,8,9])
mul=ar*ar1
print(f"Multiplication of the Two arrays = {mul} ")

Multiplication of the Two arrays = [ 50 160 270] 


In [8]:
# Div of Two Arrays
ar=np.array([10,20,30])
ar1=np.array([5,8,9])
div=ar/ar1
print(f"Sum of the Two arrays = {div} ")

Sum of the Two arrays = [2.         2.5        3.33333333] 
