In [1]:
import numpy as np
#Creating Array
#Creating 1D Array
arr=np.array([1,2,3,4])
print(f"{arr} is One Dimensional Array")

[1 2 3 4] is One Dimensional Array


In [2]:
#Now Creating a 2D Array
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"{arr1} is the Two Dimensional Array")

[[1 2 3]
 [4 5 6]
 [7 8 9]] is the Two Dimensional Array
