In [3]:
import numpy as np
#by broad casting we can add or multiply the matrices of different shapes
arr=np.array([1,2,3,4])
arr1=np.array([[10],[20],[30]])
print(f"Addition of Matrices \n{arr+arr1}") #Adding two metrices of different shape

Addition of Matrices 
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [2]:
arr=np.array([1,2,3,4])
arr1=np.array([[10],[20],[30]])
print(f"Multiplication of Matrices \n {arr*arr1}")  #Multiplying two matrices of different shape

Multiplication of Matrices 
 [[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]
