In [4]:
import numpy as np
# Array Indexing
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"This is the Array \n {arr1}")
# Now accessing the Element of Array by its Index
print("We want to target digit 6 in the Above Array so for that the indexing will be used row index=1 , column index=2 ")
a=arr1[1,2] #row index=1 , column index=2
print(a)

This is the Array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
We want to target digit 6 in the Above Array so for that the indexing will be used row index=1 , column index=2 
6


In [7]:
#Now we will select the whole row but column index=2
b=arr1[:,2]
print(b)
print("This is final array in which rows index =: , column index=2 ")

[3 6 9]
This is final array in which rows index =: , column index=2 


In [10]:
# Now we will Slice 2-7 in the given array
arr2=np.array([1,2,3,4,5,6,7,8,9])
c=arr2[1:7]
print(c)

[2 3 4 5 6 7]


In [13]:
#Reversing the Array
print(f"{arr2} This is the Original Array ")
r=arr2[::-1]
print(f"{r} This is Reversed Array")

[1 2 3 4 5 6 7 8 9] This is the Original Array 
[9 8 7 6 5 4 3 2 1] This is Reversed Array
