In [4]:
import numpy as np
arr=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])  #This is 3x4 Array we will reshape it to 4x3
print(f"Original Array \n {arr}")
reshaped=arr.reshape(4,3)
print(f"Reshaped array \n {reshaped}")

Original Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
